#ifndef SIMPLE_RAYTRACER_CONFIGURATION_H
#define SIMPLE_RAYTRACER_CONFIGURATION_H

typedef struct CONFIGURATION_Config {
  WORLD_World *world;
  CAMERA_Camera *camera;
} CONFIGURATION_Config;

#endif // SIMPLE_RAYTRACER_CONFIGURATION_H
